task :environment do
  Dir.glob(File.join(File.dirname(__FILE__), '/*.rb')).each {|f| require f }
end

task :minimax1 => :environment do
  player1 = Player.new
  player2 = Player.new
  player1.score = 19
  player2.score = 14
  board = Board.new([0, 3, 0, 5, 0, 0, 2, 2, 0, 0, 3, 0], player1, player2)
end

# BOARD 1
# 
# P1 0 3 0 5 0 0
# P2 2 2 0 0 3 0
# 
# P1 has 19
# P2 has 14
# 
# 
# BOARD 2
# 
# P1 3 0 7 1 1 3
# P2 0 2 1 4 5 1
# 
# P1 has 10
# P2 has 10
# 
# 
# BOARD 3
# 
# P1 3 4 2 1 2 2
# P2 0 3 3 6 1 0
# 
# P1 has 6
# P2 has 15 
