require 'ruby-debug'

task :environment do
  Dir.glob(File.join(File.dirname(__FILE__), '/*.rb')).each {|f| require f }
end

task :minimax1 => :environment do
  $calls_to_search = 0
  player1 = Player.new([0, 3, 0, 5, 0, 0], 19)
  player2 = Player.new([2, 2, 0, 0, 3, 0], 14)
  board = Board.new(player1, player2)
  (value, move) = Minimax.minimax(board, 10)
  puts "Best move is: ", move || "COULD NOT FIND MOVE"
  puts "Calls to search: ", $calls_to_search
end

task :minimax2 => :environment do
  $calls_to_search = 0
  player1 = Player.new([3, 0, 7, 1, 1, 3], 10)
  player2 = Player.new([0, 2, 1, 4, 5, 1], 10)
  board = Board.new(player1, player2)
  (value, move) = Minimax.minimax(board, 10)
  puts "Best move is: ", move || "COULD NOT FIND MOVE"
  puts "Calls to search: ", $calls_to_search
end

task :minimax3 => :environment do
  $calls_to_search = 0
  player1 = Player.new([3, 4, 2, 1, 2, 2], 6)
  player2 = Player.new([0, 3, 3, 6, 1, 0], 15)
  board = Board.new(player1, player2)
  (value, move) = Minimax.minimax(board, 10)
  puts "Best move is: ", move || "COULD NOT FIND MOVE"
  puts "Calls to search: ", $calls_to_search
end

task :abminimax1 => :environment do
  $calls_to_search = 0
  player1 = Player.new([0, 3, 0, 5, 0, 0], 19)
  player2 = Player.new([2, 2, 0, 0, 3, 0], 14)
  board = Board.new(player1, player2)
  (value, move) = Minimax.alpha_beta_minimax(board, 10)
  puts "Best move is: ", move || "COULD NOT FIND MOVE"
  puts "Calls to search: ", $calls_to_search
end

task :abminimax2 => :environment do
  $calls_to_search = 0
  player1 = Player.new([3, 0, 7, 1, 1, 3], 10)
  player2 = Player.new([0, 2, 1, 4, 5, 1], 10)
  board = Board.new(player1, player2)
  (value, move) = Minimax.alpha_beta_minimax(board, 10)
  puts "Best move is: ", move || "COULD NOT FIND MOVE"
  puts "Calls to search: ", $calls_to_search
end

task :abminimax3 => :environment do
  $calls_to_search = 0
  player1 = Player.new([3, 4, 2, 1, 2, 2], 6)
  player2 = Player.new([0, 3, 3, 6, 1, 0], 15)
  board = Board.new(player1, player2)
  (value, move) = Minimax.alpha_beta_minimax(board, 10)
  puts "Best move is: ", move || "COULD NOT FIND MOVE"
  puts "Calls to search: ", $calls_to_search
end
